
[project]
site_name = "FedRAMP Documentation"
site_description = "The official repository for modern FedRAMP policy and documentation."
site_author = "pete@fedramp.gov"
site_dir = "static/html/"
docs_dir = "static/markdown/"
site_url = "https://fedramp.gov/docs/"
repo_url = "https://github.com/fedramp/docs"
repo_name = "FedRAMP/docs"
nav = [
    { "General Info" = [
        "index.md",
        { "Documentation Changelog" = "changelog.md" },
        { "FedRAMP Logos" = "logos.md" },
    ] },
    { "Authority & Responsibility" = [
        "authority/index.md",
        { "Foundational Authority" = [
            "authority/index.md",
            { "FedRAMP Authorization Act" = [
                "authority/law/index.md",
                { "Definitions" = "authority/law/definitions.md" },
                { "GSA" = "authority/law/gsa.md" },
                { "FedRAMP Board" = "authority/law/board.md" },
                { "Independent Assessment" = "authority/law/assessment.md" },
                { "Agencies" = "authority/law/agencies.md" },
                { "OMB" = "authority/law/omb.md" },
                { "Reports to Congress" = "authority/law/reports.md" },
                { "FSCAC" = "authority/law/fscac.md" },
            ] },
            { "M-24-15" = [
                "authority/m-24-15/index.md",
                { "Background" = "authority/m-24-15/background.md" },
                { "Vision" = "authority/m-24-15/vision.md" },
                { "Scope of FedRAMP" = "authority/m-24-15/scope.md" },
                { "The FedRAMP Authorization Process" = "authority/m-24-15/process.md" },
                { "Automation and Efficiency" = "authority/m-24-15/automation.md" },
                { "Continuous Monitoring" = "authority/m-24-15/monitoring.md" },
                { "Roles and Responsibilities" = "authority/m-24-15/roles.md" },
                { "Industry Engagement" = "authority/m-24-15/industry.md" },
                { "Implementation" = "authority/m-24-15/implementation.md" },
                { "Rescissions" = "authority/m-24-15/rescissions.md" },
                { "Policy and Program Implementation Assistance" = "authority/m-24-15/assistance.md" },
            ] },
        ] },
        { "Related Guidance" = [
            { "Scope of FedRAMP" = "authority/scope.md" },
        ] },
        { "Historical" = [
            { "Rescinded 2011 Memo" = "authority/rescinded-2011-fedramp-memo.md" },
        ] },
    ] },
    { "FedRAMP 20x" = [
        "20x/index.md",
        { "Foundation" = [
            "20x/index.md",
            { "Definitions" = "20x/fedramp-definitions.md" },
            { "Key Security Indicators" = [
                "20x/key-security-indicators/index.md",
                { "Authorization by FedRAMP" = "20x/key-security-indicators/authorization-by-fedramp.md" },
                { "Change Management" = "20x/key-security-indicators/change-management.md" },
                { "Cloud-Native Architecture" = "20x/key-security-indicators/cloud-native-architecture.md" },
                { "Cybersecurity Education" = "20x/key-security-indicators/cybersecurity-education.md" },
                { "Identity and Access Management" = "20x/key-security-indicators/identity-and-access-management.md" },
                { "Incident Response" = "20x/key-security-indicators/incident-response.md" },
                { "Monitoring, Logging, and Auditing" = "20x/key-security-indicators/monitoring-logging-and-auditing.md" },
                { "Policy and Inventory" = "20x/key-security-indicators/policy-and-inventory.md" },
                { "Recovery Planning" = "20x/key-security-indicators/recovery-planning.md" },
                { "Service Configuration" = "20x/key-security-indicators/service-configuration.md" },
                { "Supply Chain Risk" = "20x/key-security-indicators/supply-chain-risk.md" },

            ] },
        ] },
        { "Processes" = [
            { "Authorization Data Sharing" = "20x/authorization-data-sharing.md" },
            { "Collaborative Continuous Monitoring" = "20x/collaborative-continuous-monitoring.md" },
            { "FedRAMP Security Inbox" = "20x/fedramp-security-inbox.md" },
            { "Incident Communications Procedures" = "20x/incident-communications-procedures.md" },
            { "Minimum Assessment Scope" = "20x/minimum-assessment-scope.md" },
            { "Persistent Validation and Assessment" = "20x/persistent-validation-and-assessment.md" },
            { "Secure Configuration Guide" = "20x/secure-configuration-guide.md" },
            { "Significant Change Notifications" = "20x/significant-change-notifications.md" },
            { "Using Cryptographic Modules" = "20x/using-cryptographic-modules.md" },
            { "Vulnerability Detection and Response" = "20x/vulnerability-detection-and-response.md" },
        ] },
        { "Archive" = [
            { "Phase 1" = [
                { "P1 Archive Overview" = "20x/phase1/intro.md" },
                { "P1 Key Security Indicators" = "20x/phase1/key-security-indicators.md" },
                { "P1 Minimum Assessment Standard" = "20x/phase1/minimum-assessment-standard.md" },
            ] },
        ] },
    ] },
    { "FedRAMP Rev5" = [
        "rev5/index.md",
        { "Cloud Service Providers" = [
            "rev5/playbook/csp/index.md",
            { "Getting Started" = [
                "rev5/playbook/csp/authorization/getting-started.md",
                { "Rev5 Authorization" = "rev5/playbook/csp/authorization/agency-authorization-path.md" },
                { "Partners" = "rev5/playbook/csp/authorization/partners.md" },
                { "Important Considerations" = "rev5/playbook/csp/authorization/considerations.md" },
            ] },
            { "Rev5 Authorization Packages" = [
                "rev5/playbook/csp/authorization/what.md",
                { "Roles & Responsibilities" = "rev5/playbook/csp/authorization/roles.md" },
                { "System Security Plan (SSP)" = "rev5/playbook/csp/authorization/ssp.md" },
                { "Security Assessment Plan (SAP)" = "rev5/playbook/csp/authorization/sap.md" },
                { "Security Assessment Report (SAR)" = "rev5/playbook/csp/authorization/sar.md" },
                { "Plans of Action & Milestones" = "rev5/playbook/csp/authorization/poam.md" },
            ] },
            { "Continuous Monitoring" = [
                "rev5/playbook/csp/continuous-monitoring/intro.md",
                { "Overview of Expectations" = "rev5/playbook/csp/continuous-monitoring/overview.md" },
                { "Vulnerability Scanning" = "rev5/playbook/csp/continuous-monitoring/vulnerability-scanning.md" },
                { "Annual Assessment" = "rev5/playbook/csp/continuous-monitoring/annual-assessment.md" },
                { "Significant Changes" = "rev5/playbook/csp/continuous-monitoring/significant-changes.md" },
                { "Incident Communication" = "rev5/playbook/csp/continuous-monitoring/incident-communication.md" },
                { "Collaborative ConMon" = "rev5/playbook/csp/continuous-monitoring/collaborative-monitoring.md" },
                { "Performance Management" = "rev5/playbook/csp/continuous-monitoring/performance-management.md" },
            ] },
        ] },
        { "Agencies" = [
            "rev5/playbook/agency/authorization/index.md",
            { "The FedRAMP Marketplace" = "rev5/playbook/agency/authorization/marketplace.md" },
            { "Liaison Program" = "rev5/playbook/agency/authorization/liaison-program.md" },
            { "Sponsoring Authorizations" = "rev5/playbook/agency/authorization/sponsoring.md" },
            { "Preparation" = "rev5/playbook/agency/authorization/preparation.md" },
            { "Authorization" = "rev5/playbook/agency/authorization/authorization.md" },
            { "Continuous Monitoring" = "rev5/playbook/agency/authorization/continuous-monitoring.md" },
        ] },
        { "Balance Improvement Releases" = [

            "rev5/balance/index.md",
            { "Definitions" = "rev5/balance/fedramp-definitions.md" },
            { "Mandatory for Rev5" = [
                { "Secure Configuration Guide" = "rev5/balance/secure-configuration-guide.md" },
                { "FedRAMP Security Inbox" = "rev5/balance/fedramp-security-inbox.md" },
            ] },
            { "Optional for Rev5" = [
                { "Minimum Assessment Scope" = "rev5/balance/minimum-assessment-scope.md" },
                { "Significant Change Notifications" = "rev5/balance/significant-change-notifications.md" },
                { "Authorization Data Sharing" = "rev5/balance/authorization-data-sharing.md" },
                { "Vulnerability Detection and Response" = "rev5/balance/vulnerability-detection-and-response.md" },
                { "Collaborative Continuous Monitoring" = "rev5/balance/collaborative-continuous-monitoring.md" },
            ] },
        ] },
    ] },
    { "--> return to FedRAMP.gov" = "https://fedramp.gov/" },
]

[project.extra]
homepage = "/"

[project.theme]
custom_dir = "overrides"
logo = "assets/secondary_logo.png"
language = "en"
features = [
    "announce.dismiss",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress",
    "navigation.path",
    "navigation.sections",
    "navigation.tabs",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
    "toc.follow",
]

[project.theme.icon]
repo = "fontawesome/brands/github"

[project.theme.icon.admonition]
abstract = "fontawesome/solid/gavel"

# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[project.markdown_extensions]
abbr = {}
admonition = {}
attr_list = {}
def_list = {}
footnotes = {}
md_in_html = {}
tables = {}

[project.markdown_extensions.toc]
permalink = true

[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"
