
[project]
site_name = "FedRAMP 20x Documentation"
site_description = "An experimental FedRAMP Documentation site."
site_author = "pete@fedramp.gov"
site_dir = "html"
docs_dir = "markdown"
site_url = "https://fedramp.gov/docs/20x"

nav = [
    {"Phase 2 (Current)" = [
        {"Overview" = "index.md"},
        {"Overview" = [
            {"Introduction" = "/docs"},
            {"Documentation Guidelines" = "guidelines.md"},
            {"Definitions" = "fedramp-definitions.md"},
        ]},
        {"Foundation" = [
            {"Key Security Indicators" = "key-security-indicators.md"},
            {"Minimum Assessment Scope" = "minimum-assessment-scope.md"},
            {"Using Cryptographic Modules" = "using-cryptographic-modules.md"},
        ]},
        {"Structure" = [
            {"Authorization Data Sharing" = "authorization-data-sharing.md"},
            {"Vulnerability Detection and Response" = "vulnerability-detection-and-response.md"},
            {"Significant Change Notifications" = "significant-change-notifications.md"},
            {"Collaborative Continous Monitoring" = "collaborative-continuous-monitoring.md"},
            {"Recommended Secure Configuration" = "recommended-secure-configuration.md"},
            {"FedRAMP Security Inbox" = "fedramp-security-inbox.md"},
            {"Persistent Validation and Assessment" = "persistent-validation-and-assessment.md"},
            {"Incident Communications Procedures" = "incident-communications-procedures.md"},            
        ]}
    ]},
    {"Phase 1 (Archive)" = [
        {"P1 Intro" = "phase1/intro.md"},
        {"P1 Key Security Indicators" = "phase1/key-security-indicators.md"},
        {"P1 Minimum Assessment Standard" = "phase1/minimum-assessment-standard.md"}
    ]}, 
    {"// Return to fedramp.gov" = "https://fedramp.gov/20x/phase-two"}
]

[project.extra]
homepage = "https://fedramp.gov/docs"

[project.theme]
logo = "assets/fedramp-logo-just-letters.svg"
custom_dir = "tools/overrides"
language = "en"
features = [
    "announce.dismiss",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress",
    "navigation.sections",
    "navigation.tabs",
    "navigation.top",
    "navigation.tracking",
    "navigation.path",
    "search.highlight",
    "toc.follow",
]

[project.theme.icon.admonition]
abstract = "fontawesome/solid/gavel"

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"


#[project.markdown_extensions.abbr]
#[project.markdown_extensions.attr_list]
#[project.markdown_extensions.pymdownx.snippets]
#auto_append = ["overrides/definitions.md"]