
[project]
site_name = "FedRAMP Documentation"
site_description = "An experiment FedRAMP Documentation site."
site_author = "pete@fedramp.gov"
site_dir = "site"
docs_dir = "docs"

nav = [
    {"Overview" = [
        "index.md" 
    ]},
    {"20x Phase One" = [
        {"Intro" = "20xP1/intro.md"},
        {"Key Security Indicators" = "20xP1/FRMR.KSI.key-security-indicators.md"},
        {"Minimum Assessment Standard" = "20xP1/FRMR.MAS.minimum-assessment-standard.md"},
    ]},
    {"20x Phase Two" = [
        {"Intro" = "20xP2/intro.md"}, 
        {"Definitions" = "20xP2/FRMR.FRD.fedramp-definitions.md"},
        {"Key Security Indicators" = "20xP2/FRMR.KSI.key-security-indicators.md"},
        {"Minimum Assessment Standard" = "20xP2/FRMR.MAS.minimum-assessment-standard.md"},
        {"Authorization Data Sharing" = "20xP2/FRMR.ADS.authorization-data-sharing.md"},
        {"Vulnerability Detection and Response" = "20xP2/FRMR.VDR.vulnerability-detection-and-response.md"},
        {"Significant Change Notification" = "20xP2/FRMR.SCN.significant-change-notifications.md"},
        {"Collaborative Continous Monitoring" = "20xP2/FRMR.CCM.collaborative-continuous-monitoring.md"},
        {"Recommended Secure Configuration" = "20xP2/FRMR.RSC.recommended-secure-configuration.md"},
        {"Incident Communications Procedures" = "20xP2/FRMR.ICP.incident-communications-procedures.md"},
        {"Using Cryptographic Modules" = "20xP2/FRMR.UCM.using-cryptographic-modules.md"},
    ]},
    {"Rev5" = [
        {"Intro" = "Rev5/intro.md"}, 
        {"Page 1" = "section/page-1.md"},
    ]},
    {"// Return to fedramp.gov" = "https://fedramp.gov"}
]

[project.extra]
homepage = "https://fedramp.gov"


[project.theme]
logo = "assets/fedramp-logo-just-letters.svg"
custom_dir = "overrides"
language = "en"
features = [
    "announce.dismiss",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    "navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.path",
    "navigation.sections",
    "navigation.tabs",
    "navigation.top",
    "navigation.tracking",
    "search.highlight",
    "toc.follow",
]

[project.theme.icon.admonition]
abstract = "fontawesome/solid/gavel"

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
